component: http
name: egg_server
stage: dev
inputs:
  region: ap-shanghai
  src:
    src: ./
    exclude:
      - .env
  faas:
    runtime: Nodejs12.16
    framework: egg
    name: ${name}
  apigw:
    protocols:
      - http
      - https
app: egg_server_app
